name: Patrolio Inactive Sessions

# Trigger workflow manually or on schedule
on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes UTC
  workflow_dispatch:  # allows manual trigger

jobs:
  call_inactive_sessions:
    runs-on: ubuntu-latest

    steps:
      - name: Print workflow start
        run: |
          echo "Workflow started at $(date -u) UTC"
          echo "Workflow started at $(TZ='America/New_York' date) ET"

      - name: Call Patrol API for inactive sessions
        env:
          BACKEND_API_KEY: ${{ secrets.BACKEND_API_KEY }}
        run: |
          echo "Calling inactive_sessions API..."
          curl -H "X-API-KEY: $BACKEND_API_KEY" \
               -X GET "https://patrolio-patrol-sessions.onrender.com/inactive_sessions/15"
          echo "API call completed at $(date -u) UTC"
